### PR TITLE
Update project to new ember-cli and add Fastboot 1.0.0 support

### PR DESCRIPTION
**Pull request by jurecuhalev**
First, sorry for this large Pull Request. I've had problems in getting tests to work with my previous PR. So I started with a fresh project that uses up to date requirements for new ember projects/addons.

Implemented in this PR:

- webfontloader.js is now loaded through node_modules
- updated shim structure
- implements Fastboot 1.0.0 style initializers
- adds Fastboot 1.0.0 support
- removes the dependancy on bower.json

Looking at how other addons solve the Fastboot 1.0.0 breakage/support, I would suggest maybe tagging this as 0.4.0 release and requiring Ember 2.x and Fastboot 1.0.0 to use.

I understand that this is a large change to the addon and that you're not actively using Ember anymore. I'm happy to stick around for a while and help with any issues that crop up because of this.

### CODE REVIEW

**Comment by kuzzmi** [comment]
First, thank you a lot for the great job! :+1:

Seems a lot, but legit. I'm gonna merge this and will publish v1.0.0 so updates to README.md are required to make sure the versions are mentioned correctly.

**Comment by jurecuhalev** [comment]
Do you want me to update README/versions?

**Comment by kuzzmi** [comment]
Okay, I updated, merged and published as 0.4.0. Too early for 1.0.0, I believe

**Comment by jurecuhalev** [comment]
Thanks!

**Pull request merged**
